### ISSUE TITLE
Buefy Theme

### ISSUE THREAD

**Issue by STnetwork** [nakorndev/vuepress-theme-bulma#8]
Hi,

Thanks a lot for your vuepress-theme-bulma, could you tell me who I can use Buefy in your theme ?

Thanks in advance.

**Comment by nakorndev** [comment]
I updated at branch name `buefy-demo` URL: [https://github.com/nakorndev/vuepress-theme-bulma/tree/buefy-demo](https://github.com/nakorndev/vuepress-theme-bulma/tree/buefy-demo)

This commit should help you understand to use Buefy [https://github.com/nakorndev/vuepress-theme-bulma/commit/c96f33fdaa2d3f47291d3cd818da33a674791581](https://github.com/nakorndev/vuepress-theme-bulma/commit/c96f33fdaa2d3f47291d3cd818da33a674791581)
